# docker-compose.override.yml
services:
  rag-app:
    build:
      dockerfile: .devcontainer/Dockerfile.cpu
      args:
        TorchVer_CPU: "2.6.0+cpu"
        TorchVisionVer_CPU: "0.21.0+cpu"
    environment:
      OLLAMA_MODEL: phi4-mini
