# docker-compose.cpu.yml
services:
  ragapp:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        TorchVer: "2.6.0+cpu"
        TorchVisionVer: "0.21.0+cpu"
    image: ragapp
    pull_policy: never 
    container_name: ragapp
    volumes:
      - .:/workspace
    networks:
      - ragnet
    extra_hosts:
      - "host.docker.internal:172.20.0.1" #host-gateway
    ports:
      - "8501:8501"
    tty: true
    stdin_open: true 
    command:
      - bash
      - -l
    environment:
      DB_HOST: ragdb
      OLLAMA_MODEL: phi4-mini
      OLLAMA_BASE: http://host.docker.internal:11434
      DB_URL: postgresql://raguser:ragpass@ragdb:5432/ragdb
      PYTHONPATH: /workspace
      STREAMLIT_SERVER_ADDRESS: 0.0.0.0
      STREAMLIT_SERVER_PORT: 8501
      STREAMLIT_SERVER_ENABLE_CORS: "false" # ""必須

networks:
  ragnet:
    external: true
    name: ragnet
