name: rag_env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - python-docx
  - langdetect
  - sqlalchemy
  - mecab-python3
  - pip
  - gcc_linux-64
  - gxx_linux-64
  - pip:
      - pymupdf==1.22.3
      - opencv-python
      - pdf2image
      - Pillow
      - langchain
      - langchain-ollama
      - numpy<2
      - torch==2.2.2
      - torchvision==0.17.2
      - sentence-transformers
      - psycopg2-binary
      - openai
      - faiss-cpu
      - transformers==4.40.1
      - fugashi
      - ipadic
      - unidic-lite
      - pytesseract
      - langchain-community
      - timm
      - streamlit
